### PR TITLE
FHIR-40697, FHIR-40684, FHIR-39726, FHIR-40241

### PR DESCRIPTION
**Pull request by dand9959**
https://jira.hl7.org/browse/FHIR-40697 
    Relaxed cardinality in Computable measure cqfm extension for 'cqfm-type' to 0..* from 0..1

https://jira.hl7.org/browse/FHIR-40684
    Relaxed introduction statement about QI Core

https://jira.hl7.org/browse/FHIR-39726
   Fixed link for Colorectal Cancer Screening example on examples page

https://jira.hl7.org/browse/FHIR-40241
   Clarified definition wording for usage element of Publishable Measure CQFM
   Note that this ticket also called for setting cardinality of 'guidance' to 0..0 as it was to be removed.  Apparently, that removal has already happened  (See resolved/published ticket https://jira.hl7.org/browse/FHIR-39605 )

### CODE REVIEW

**Review by abdullah-git1 — APPROVED** [review]
Looks good!

**Review by abdullah-git1 — APPROVED** [review]
Link looks good

**Comment by dand9959** [comment]
Changed cardinallity to 0.0.  (See commit [50bbbb7](https://github.com/HL7/cqf-measures/pull/114/commits/50bbbb7c64c8c061b3c14a67125647d7cacb72ca)

https://tracker.esacinc.com/browse/CQF-1738

**Review by abdullah-git1 — APPROVED** [review]
Looks good!

**Pull request merged**
